name: learnphysicspartII
version: 0.1.0.0
github: "githubuser/learnphysicspartII"
license: BSD-3-Clause
author: "Esteban Marin"
maintainer: "estebanmarin002@gmail.com"
copyright: "2024 Esteban Marin"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/learnphysicspartII#readme>

dependencies:
  - base >= 4.7 && < 5
  - gnuplot

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - gnuplot

executables:
  learnphysicspartII-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - learnphysicspartII

tests:
  learnphysicspartII-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - learnphysicspartII
